### ISSUE TITLE
Client not connecting to the Network

### ISSUE THREAD

**Issue by DerpyDoom** [standard-error/electrum-raven#29]
Hi, one evening it worked fine. I was even able to transfe 50 RVN. A day later now I can't sync with the network since it always says no connection. Tried everything - Reboot PC - Reboot the Client. Nothing.

**Comment by brokdikdog** [comment]
Is there another server that the wallet can connect to? I can ping the server fine but as of this morning my electrum-raven wallet no longer connects and updates transactions.

INFO | network | couldn't launch iface electrumx-rvn.nbits.dev:50002:s -- CancelledError()
INFO | network | connecting to electrumx-rvn.nbits.dev:50002:s as new interface
INFO | network | network: retrying connections
INFO | interface.[electrumx-rvn.nbits.dev:50002] | disconnecting due to: ConnectError(TimeoutError(10060, "Connect call failed ('216.127.187.104', 50002)"),)

**Comment by amd1361** [comment]
I have the same problem with the connection to the server
![not connected](https://user-images.githubusercontent.com/35899329/109400102-f7203500-795b-11eb-8148-6d5ebe354ed9.png)

**Comment by KedarThakur** [comment]
I am unable to connect too....
Is there another server we can use?
Or can someone explain how to host your own server??

**Comment by brokdikdog** [comment]
I just started using https://wallet.chaintek.net until it gets resolved. I was able to use my nano s to view my wallet there. In Brave or Chrome you have to enter "chrome://flags/#new-usb-backend" and change default to disabled and then you are able to unlock your wallet right away.

**Comment by Monkey-D-Garp** [comment]
can i get my ravencoin's without a hardware wallet?

**Comment by Kaezon** [comment]
@KedarThakur @brokdikdog @Monkey-D-Garp @DerpyDoom
I built a new ElectrumX server from kyuupichan/electrumx v1.15
You can access it at electrum-rvn.dnsalias.net for now.
I'm not sure how permanent this node will be, but I'm going to work on documenting it in the next few days so other folks can spin nodes as well.

**Comment by deniben** [comment]
![image](https://user-images.githubusercontent.com/19304301/109467417-cfbc8b80-7a73-11eb-8efc-b2214cc3e62a.png)
I have the same problem, not connected!

**Comment by Kaezon** [comment]
@deniben Try configuring to use my node like this
![image](https://user-images.githubusercontent.com/1547901/109468257-5785a400-7a3a-11eb-9f02-8497677aed92.png)

**Comment by deniben** [comment]
> @deniben Try configuring to use my node like this
> ![image](https://user-images.githubusercontent.com/1547901/109468257-5785a400-7a3a-11eb-9f02-8497677aed92.png)

is it safe?

**Comment by Kaezon** [comment]
> > @deniben Try configuring to use my node like this
> 
> is it safe?

I'm the one running it, so I'd say yes of course XD

As I mentioned above, I'm going to document it so other folks can run their own.
I just wanted to make my node public so people could get to their wallets.

**Comment by deniben** [comment]
> > > @deniben Try configuring to use my node like this
> > 
> > 
> > is it safe?
> 
> I'm the one running it, so I'd say yes of course XD
> 
> As I mentioned above, I'm going to document it so other folks can run their own.
> I just wanted to make my node public so people could get to their wallets.

thanks it works!

**Comment by Monkey-D-Garp** [comment]
no offence but what could happen in the worst case if i use an insecure server?

**Comment by Kaezon** [comment]
> no offence but what could happen in the worst case if i use an insecure server?

I'm still new to this, but as far as I can see, Electrum acts as a relay system. Ravend is keeping a copy of the blockchain up to day, and electrumx is indexing it so that clients can interact with the blockchain without having to download it.

The electrum server does not get any of your wallet keys, so like any zero trust system, a malicious server couldn't break into your wallet.
I think a malicious server might be able to censor transactions by choosing to selectively ignore traffic from one host or another.
The trust issue is why I'm going to document the build this week though. It'd be better if there was more than just one or two nodes out there after all.

**Comment by Kaezon** [comment]
Oh hey, someone beat me to it!
HyperPeek on the Ravencoin Community Discord made it.
[Setup_of_electrumx_server_for_rvn.pdf](https://github.com/standard-error/electrum-raven/files/6064779/Setup_of_electrumx_server_for_rvn.pdf)

**Comment by Kaezon** [comment]
Heads up for everyone. HyperPeek is hosting two more nodes at the following addresses:
ravennode-01.beep.pw
ravennode-02.beep.pw

I'd encourage folks to add both to decrease reliance on a single node. Especially since I'm going to do further work on my node, which will make it periodically unavailable.

**Comment by martintokman** [comment]
Hi, im getting problems tryting to connect my electrum rvn wallet to a server, i always have the red dot on the bottom right corner.

I have changed to other servers like ravennode-01.beep.pw or electrum-rvn.dnsalias.net but i cant connect. Also have the same issue and error on ravennode-02.beep.pw

on the log viewer i see this error 

INFO | interface.[ravennode-01.beep.pw:50002] | can't connect 1650748
INFO | interface.[ravennode-01.beep.pw:50002] | requesting block header 338688 in mode backward
INFO | network | switching to ravennode-01.beep.pw:50002:s
ERROR | interface.[ravennode-01.beep.pw:50002] | Exception in wrapper_func: InvalidHeader('Invalid header length: 80',)

I have Electrum-raven 3.3.8-rvn3

Kind regards

**Comment by Kaezon** [comment]
@martintokman You're having a sync issue related to the old block header size.
Check out the notes on the latest release here: https://github.com/standard-error/electrum-raven/releases
Download the "block_headers" artifact and place it in the directory documented in the notes there.

**Comment by martintokman** [comment]
Thanks @Kaezon , it works great for me. The problem is now solved. Thanks a lot for your help. Have a nice day

**Comment by Bertrand-92** [comment]
Hello Keazon I have the same problem connecting to the server as martinokman, I have version 3.3.8-rvn and even with your personal server it still does not work.
Could you direct me where we have to put the blockchain_headers (Windows) I can't find the location.
thank you for your advice

**Comment by Kaezon** [comment]
@Bertrand-92 The direct link is https://github.com/standard-error/electrum-raven/releases/download/3.3.8-rvn3/blockchain_headers

According to the release notes, you need to place the file in Users\UserName\AppData\Roaming\Electrum-raven\blockchain_headers (for Windows)

**Comment by horca17** [comment]
I had the same problem on Mac, by changing the blockchain_headers file loaded on install, /.electrum-raven/blockchain_headers, with the one on https://github.com/standard-error/electrum-raven/releases/download/3.3.8-rvn3 make it work and sync.

**Comment by Bertrand-92** [comment]
in fact I don't have the blockchain_headers file in the electrum-rvn-3.3.8-rvn3 installation files
so I can't replace it with the one you gave me

**Comment by Yul1122** [comment]
> @Bertrand-92 The direct link is https://github.com/standard-error/electrum-raven/releases/download/3.3.8-rvn3/blockchain_headers
> 
> According to the release notes, you need to place the file in Users\UserName\AppData\Roaming\Electrum-raven\blockchain_headers (for Windows)

I

> @Bertrand-92 The direct link is https://github.com/standard-error/electrum-raven/releases/download/3.3.8-rvn3/blockchain_headers
> 
> According to the release notes, you need to place the file in Users\UserName\AppData\Roaming\Electrum-raven\blockchain_headers (for Windows)

 I don't have the blockchain_headers file in the electrum-rvn folder. so I can't replace it. How can resolve this problem?

**Comment by Yul1122** [comment]
> @Bertrand-92 The direct link is https://github.com/standard-error/electrum-raven/releases/download/3.3.8-rvn3/blockchain_headers
> 
> According to the release notes, you need to place the file in Users\UserName\AppData\Roaming\Electrum-raven\blockchain_headers (for Windows)

I don't have the blockchain_headers file in the electrum-rvn folder. so I can't replace it. How can resolve this problem?

**Comment by Kaezon** [comment]
@Bertrand-92 I reviews the location where I dropped my portable install, and it dropped the data directory in the same location where the .exe was.

So I'd check {whever_electrum_is}/electrum-rvn_data for the file, if the file or the directory is missing, I'd just try creating it there and seeing if it fixes the issue.

**Comment by Yul1122** [comment]
> @Bertrand-92 I reviewed the location where I dropped my portable install, and it dropped the data directory in the same location where the .exe was.
> 
> So I'd check {whever_electrum_is}/electrum-rvn_data for the file, if the file or the directory is missing, I'd just try creating it there and seeing if it fixes the issue.

Thank you for your help.
I tried creating it in Electrum RVN folder, but it's still not connected. 
I can see my balance, it means I have my RVN in ledger, not hacked, right? I'm just worried about being hacked.

**Comment by Yul1122** [comment]
> @Yul1122 I don't suspect there's been a hack. As long as your wallet isn't connecting, you're effectively seeing the blockchain some time in the past. It won't update to reflect any changes in your balance until the client can download newer headers from a server.
> 
> Are you still getting "Exception in wrapper_func: InvalidHeader('Invalid header length: 80',)" in your logs?

I bought a new laptop today, installed Electrum there and tried to connect the Ledger but It didn't work. 
And then I tried to connect Electrum in the old laptop , but it didn't work, too. It connected 2-3 weeks ago, but not today. 

Could it be a problem trying to connect on a new laptop?

I can see green light on the ledger mark  and a red circle next to it at the bottom.

I don't see "Exception in wrapper_func: InvalidHeader('Invalid header length: 80',)" 

I appreciate your help.

**Comment by Kaezon** [comment]
@Yul1122 I apologize, I think I got confused somewhere.

Just so I'm clear on what you're seeing, is this what your indicators look like?
![image](https://user-images.githubusercontent.com/1547901/110421966-7accd680-806c-11eb-90e5-f2a960b39993.png)

**Comment by Yul1122** [comment]
> @Yul1122 I apologize, I think I got confused somewhere.
> 
> Just so I'm clear on what you're seeing, is this what your indicators look like? (red outline added by me)
> ![image](https://user-images.githubusercontent.com/1547901/110421966-7accd680-806c-11eb-90e5-f2a960b39993.png)

It's opposite. Red bigger circle and green smaller circle on ledger mark.

**Comment by Kaezon** [comment]
Ok, so it's still a network issue of some kind.
What errors are you seeing in the log viewer?

**Comment by Yul1122** [comment]
> Ok, so it's still a network issue of some kind.
> What errors are you seeing in the log viewer?

![20210309_003007](https://user-images.githubusercontent.com/80299303/110423211-a51f9380-806e-11eb-94ba-ca9528d8abc9.jpg)
![20210309_002948](https://user-images.githubusercontent.com/80299303/110423214-a650c080-806e-11eb-9e4a-b9cd793751a2.jpg)

I don't see ant error in the log viewer. After log in, I can see like pictures.

**Comment by Kaezon** [comment]
I'm afraid I'm not sure where I can begin helping you if there's nothing in the logs.
Make sure logs are being written to file in you preferences under the general tab:
![image](https://user-images.githubusercontent.com/1547901/110423775-af8e5d00-806f-11eb-8b2a-ce9270d64588.png)

As long as that's set, maybe share anything by copying it from the log viewer or by copying out of the file. Those are stored in the electrum-rvn_data/logs directory if you need to find them.

There shouldn't be any sensitive information in those logs, but please review them and redact any information you might be worried about before sharing.

**Comment by Yul1122** [comment]
> I'm afraid I'm not sure where I can begin helping you if there's nothing in the logs.
> Make sure logs are being written to file in you preferences under the general tab:
> ![image](https://user-images.githubusercontent.com/1547901/110423775-af8e5d00-806f-11eb-8b2a-ce9270d64588.png)
> 
> As long as that's set, maybe share anything by copying it from the log viewer or by copying out of the file. Those are stored in the electrum-rvn_data/logs directory if you need to find them.
> 
> There shouldn't be any sensitive information in those logs, but please review them and redact any information you might be worried about before sharing.

Thank you so much for the detailed answer despite being late.

English is not my first language, so I have a little difficulty understanding.

"write logs to file" was not checked.

**Comment by Kaezon** [comment]
No problem :)
Just let me know what errors you see when they pop up.

**Comment by Yul1122** [comment]
> No problem :)
> Just let me know what errors you see when they pop up.

![20210309_010010](https://user-images.githubusercontent.com/80299303/110425882-16614580-8073-11eb-8389-6232acba438c.jpg)

You mean this one?😅

**Comment by Kaezon** [comment]
I think the "Write logs to file" setting is unchecked again in that image.

I have made a more detailed picture for you.

1.) Turn on "Write to logs"
2.) Open "Log viewer"
2a.) Close Electrum
2b.) Open Electrum
3.) Look for lines that start with "ERROR | "
![image](https://user-images.githubusercontent.com/1547901/110426687-858b6980-8074-11eb-8f77-31d4b838e84b.png)

**Comment by Yul1122** [comment]
> I think the "Write logs to file" setting is unchecked again in that image.
> 
> I have made a more detailed picture for you.
> 
> 1.) Turn on "Write to logs"
> 2.) Open "Log viewer"
> 2a.) Close Electrum
> 2b.) Open Electrum
> 3.) Look for lines that start with "ERROR | "
> ![image](https://user-images.githubusercontent.com/1547901/110426687-858b6980-8074-11eb-8f77-31d4b838e84b.png)

👍👍👍👍
Thanks to your detailed description, I found the log Viewer.

**Comment by Kaezon** [comment]
This is a failure to connect to the old server.

Here is more instructions for adding servers:

1.) Open "Network"
2.) Turn off "Select server automatically"
3.) Type in "ravennode-02.beep.pw" and "50002"
3a.) Wait a short time for the new server to appear below
3b.) Repeat to add "ravennode-01.beep.pw" and "electrumx-rvn.dnsalias.net"
4.) The list should look like this when you are done.

![image](https://user-images.githubusercontent.com/1547901/110430063-cfc31980-8079-11eb-8d4c-3df44fe0e090.png)

**Comment by Yul1122** [comment]
> This is a failure to connect to the old server.
> 
> Here is more instructions for adding servers:
> 
> 1.) Open "Network"
> 2.) Turn off "Select server automatically"
> 3.) Type in "ravennode-02.beep.pw" and "50002"
> 3a.) Wait a short time for the new server to appear below
> 3b.) Repeat to add "ravennode-01.beep.pw" and "electrumx-rvn.dnsalias.net"
> 4.) The list should look like this when you are done.
> 
> ![image](https://user-images.githubusercontent.com/1547901/110430063-cfc31980-8079-11eb-8d4c-3df44fe0e090.png)

Now it works. It's not enough to say thank you so much. You saved me. Thank you very much.

**Comment by Bertrand-92** [comment]
hello Keazon after following your recommendations I checked the log viewer option, I removed the automatic selection of servers and wrote the 4 servers as you recommended but I still can not be connected
I have this in error in the log
INFO | network | connecting to electrum-rvn.dnsalias.net:50002:s as new interface
INFO | interface. [electrum-rvn.dnsalias.net:50002] | connection established. version: ['ElectrumX 1.15.0', '1.4']
INFO | interface. [electrum-rvn.dnsalias.net:50002] | set blockchain with height 338687
INFO | interface. [electrum-rvn.dnsalias.net:50002] | can't connect 1660669
INFO | interface. [electrum-rvn.dnsalias.net:50002] | requesting block header 338688 in backward mode
INFO | network | switching to electrum-rvn.dnsalias.net:50002:s
ERROR | interface. [electrum-rvn.dnsalias.net:50002] | Exception in wrapper_func: InvalidHeader ('Invalid header length: 80',)

I specify that I still have not changed the blockchain_headers because I do not have an electrum-rvn_data folder in the installation files

Thanks for the time to help me

**Comment by martintokman** [comment]
Hi @Bertrand-92 , if you are using windows.., did you check into te \user\AppData\Roaming folder? it is usually a hidden folder so if you dont see it you have to change your Windows config to show hidden files/folders.

Regards

**Comment by Bertrand-92** [comment]
Hello martintokman, I have just made the modification of the configuration of the hidden files and I still do not have the \ user \ AppData \ Roaming folder

**Comment by Bertrand-92** [comment]
finally I just found it in the hidden files, I modified the blockchain_headers and it works now

A big thank you to @Kaezon and @martintokman I could never thank you enough for finding me the solution

**Comment by alipm27** [comment]
Hello, is there anyone here who can help me?
I can not connect the ledger to the electro wallet.
It does not detect my device.
Has trouble creating cclients.
And I see these messages
Failed to create a client for this device
Make sure it is in the correct state
Device must be unlocked with the Ravencoin app open.
